"""
Code to clear all the saved files generated by extraction
"""
from modules.data import Data

import os

dict_variables = Data().load_yaml("variables.yaml")
list_directories = [dict_variables["dir_results"], "generated_tables"]

for dir in list_directories:
    for filename in os.listdir(dir):
        os.remove(os.path.join(dir, filename))